ui:
  title: "Détection et comptage automatique"
  theme_color: "#981d97"
  page_threshold: 100
  show_visualization: true  # Permet d'afficher ou de masquer tout le panneau de droite (tableaux et images)
  logos:
    top_left_1: "logo_ecrins.png"
    top_left_2: "logo_lacs.png"
    top_right_1: "logo_leca.png"
    top_right_2: "BiodivTourAlps_logo_def.png"

models:
  available:
    - YOLO
    - SAM3
  device: "cpu"  # "cuda" pour utiliser la carte graphique, "cpu" pour utiliser le processeur
  default_confidence: 0.4
  show_confidence_slider: true  # Permet de masquer le slider de confiance (utilisera la valeur par défaut)
  confidence_range: [0.1, 0.9]

features:
  allow_tiling: true  # Permet de masquer entièrement l'option de Tiling si configuré sur false
  classes:
    - tente
    - baigneur

ofb_attendance:
  ftp_server: ""
  ftp_username: "username"
  ftp_port: 21
  ftp_password: "mdp"
  ftp_directory: "/images_folder"
  local_folder: "/home/lweksteen/test"
  output_folder: "/home/lweksteen/test/output"
  model_name_pose: "yolov8m-pose.pt"
  treshold_pose: 0.3
  model_name_google: "yolov8m-oiv7.pt"
  treshold_google: 0.1
  image_or_time_csv: "time"
  sequence_duration: 10
  time_step: "h"
  output_format: "csv"
  blur: false