services:
  app:
    image: ghcr.io/pnecrins/cairn:latest
    ports:
      - "80:7860"
    volumes:
      - ./model_weights:/app/model_weights
      - ./config.yaml:/app/config.yaml
      # - ./assets:/app/assets # uncommment if you want to add and use your own logos
